### ISSUE TITLE
System Messages DataList is not bootstraped

### ISSUE THREAD

**Issue by ikaygorodov** [Redpill-Linpro/alfresco-systemmessages#6]
Please make a bootstrap or at least show the code to create correct datalist.
After Installing 1.1.0-SNAPSHOT when opening "System Messages" topic in Admin console, I'm getting the following error:
[System Messages Exception.txt](https://github.com/Redpill-Linpro/alfresco-systemmessages/files/883287/System.Messages.Exception.txt)

After creating a simple datalist (Repository> Data Dictionary> dataLists> system-messages-datalist) using code:
```
var dataLists = search.findNode("workspace://SpacesStore/274ac34d-b439-4f5d-bec8-375c0b2e2234");
var list = dataLists.createNode("system-messages-datalist","dl:dataList");
```

It works, but there is no way to deleted message (I suppose that the reason is incorrect Datalist)

**Comment by billerby** [comment]
@ikaygorodov which version of Alfresco are you running?

**Comment by ikaygorodov** [comment]
@billerby 5.1.2 Enterprise

**Comment by billerby** [comment]
Ok, I have deployed 1.1.0-SNAPSHOT to our maven repo with a possible fix. However, I think you may need to delete that datalist you created by yourself first. I have no running 5.1.x instance to test the fix on but it should do since it was just a version number of the alfresco schema that was causing the patch to not run. Could you test this out, and report back? I will make a release if it works.

**Comment by billerby** [comment]
Fixed in 1.1.0

**Comment by ikaygorodov** [comment]
@billerby Sorry for delay.
Unfortunately bootstrap still does not work. But now Deletion works even if I'm creating datalist with script above.

**Comment by billerby** [comment]
Well I tested it out with a vanilla 5.2 before releasing and it worked. Please provide a log file so I have a chance to find out whats wrong.

**Comment by ikaygorodov** [comment]
@billerby Alfresco startup log?

**Comment by billerby** [comment]
Yeah, exactly. In the bootstraping process, just after the log statment:

`INFO  [org.alfresco.repo.admin.patch.PatchExecuter] Checking for patches to apply ...`

There will be an exception if the patch fails. I need that stacktrace.
